### ISSUE TITLE
Feature Request: Rescue jobs, tasks, etc

### ISSUE THREAD

**Issue by ericboehs** [erichaydel/errdo#2]
I've been using Rollbar and Raygun recently. They monitor more than just web requests. And, from what I can tell, errdo just rescues web requests.

It would be nice to monitor scripts fired by a scheduler (e.g. cron), rake tasks and ActiveJobs.

It would also be nice to fire warnings as a sort of logger (e.g. Rollbar.warn).

**Comment by erichaydel** [comment]
This is a great idea. 

For the warn, how do those systems treat it? Is it treated as a regular error?

**Comment by ericboehs** [comment]
Rollbar lumps everything together as "Items". They have multiple "levels". An exception is an "error". They also have critical, warning, info, and debug. So it's sort of like Rails.logger except it doesn't get mixed in with your other logs and you get to see occurrence count, users affected, timestamps, server ids and pids, as well as the ability to comment/assign/resolve.

Here's their docs on it https://rollbar.com/docs/notifier/rollbar-gem/#caught-exceptions-and-messages

**Comment by erichaydel** [comment]
I forgot to post here after updating, but I've added the ability to manually log and notify in the newest release, 0.11.0
Still working on getting it to work with active jobs

**Comment by ericboehs** [comment]
That's great! At least I can manually log in jobs now. Thanks!

**Comment by erichaydel** [comment]
So both active jobs and rake tasks are supported now. Hope it works well for you.

Let me know if you have any more feedback.
I've put a task to filter errors on the dashboard, so that should come pretty soon.

**Comment by ericboehs** [comment]
Awesome. Thanks so much!
