### ISSUE TITLE
Split Gem

### ISSUE THREAD

**Issue by ened** [erichaydel/errdo#24]
For some projects, it might be helpful to only use the error recording & notification part and Skip the View entirely.

The standard `errdo` gem could become sth. like an umbrella component which links to both `errdo-view`, `errdo-notifier` and those could depend on `errdo-common`.

Similar to how `kaminari` handles it.

**Comment by erichaydel** [comment]
I don't really plan on doing this because I think it's useful mostly as a small, tight package without multiple gems.
